/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flatfile.api.resources.records.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.flatfile.api.core.ObjectMappers;
import com.flatfile.api.resources.commons.types.RecordId;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = RecordWithLinks.Builder.class)
public final class RecordWithLinks {
    private final RecordId id;

    private final RecordDataWithLinks values;

    private final Optional<Boolean> valid;

    private final Optional<List<ValidationMessage>> messages;

    private final Optional<Map<String, Object>> metadata;

    private final Optional<RecordConfig> config;

    private final Map<String, Object> additionalProperties;

    private RecordWithLinks(
            RecordId id,
            RecordDataWithLinks values,
            Optional<Boolean> valid,
            Optional<List<ValidationMessage>> messages,
            Optional<Map<String, Object>> metadata,
            Optional<RecordConfig> config,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.values = values;
        this.valid = valid;
        this.messages = messages;
        this.metadata = metadata;
        this.config = config;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("id")
    public RecordId getId() {
        return id;
    }

    @JsonProperty("values")
    public RecordDataWithLinks getValues() {
        return values;
    }

    @JsonProperty("valid")
    public Optional<Boolean> getValid() {
        return valid;
    }

    @JsonProperty("messages")
    public Optional<List<ValidationMessage>> getMessages() {
        return messages;
    }

    @JsonProperty("metadata")
    public Optional<Map<String, Object>> getMetadata() {
        return metadata;
    }

    @JsonProperty("config")
    public Optional<RecordConfig> getConfig() {
        return config;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof RecordWithLinks && equalTo((RecordWithLinks) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(RecordWithLinks other) {
        return id.equals(other.id)
                && values.equals(other.values)
                && valid.equals(other.valid)
                && messages.equals(other.messages)
                && metadata.equals(other.metadata)
                && config.equals(other.config);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.values, this.valid, this.messages, this.metadata, this.config);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        ValuesStage id(RecordId id);

        Builder from(RecordWithLinks other);
    }

    public interface ValuesStage {
        _FinalStage values(RecordDataWithLinks values);
    }

    public interface _FinalStage {
        RecordWithLinks build();

        _FinalStage valid(Optional<Boolean> valid);

        _FinalStage valid(Boolean valid);

        _FinalStage messages(Optional<List<ValidationMessage>> messages);

        _FinalStage messages(List<ValidationMessage> messages);

        _FinalStage metadata(Optional<Map<String, Object>> metadata);

        _FinalStage metadata(Map<String, Object> metadata);

        _FinalStage config(Optional<RecordConfig> config);

        _FinalStage config(RecordConfig config);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements IdStage, ValuesStage, _FinalStage {
        private RecordId id;

        private RecordDataWithLinks values;

        private Optional<RecordConfig> config = Optional.empty();

        private Optional<Map<String, Object>> metadata = Optional.empty();

        private Optional<List<ValidationMessage>> messages = Optional.empty();

        private Optional<Boolean> valid = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(RecordWithLinks other) {
            id(other.getId());
            values(other.getValues());
            valid(other.getValid());
            messages(other.getMessages());
            metadata(other.getMetadata());
            config(other.getConfig());
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public ValuesStage id(RecordId id) {
            this.id = id;
            return this;
        }

        @java.lang.Override
        @JsonSetter("values")
        public _FinalStage values(RecordDataWithLinks values) {
            this.values = values;
            return this;
        }

        @java.lang.Override
        public _FinalStage config(RecordConfig config) {
            this.config = Optional.of(config);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "config", nulls = Nulls.SKIP)
        public _FinalStage config(Optional<RecordConfig> config) {
            this.config = config;
            return this;
        }

        @java.lang.Override
        public _FinalStage metadata(Map<String, Object> metadata) {
            this.metadata = Optional.of(metadata);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "metadata", nulls = Nulls.SKIP)
        public _FinalStage metadata(Optional<Map<String, Object>> metadata) {
            this.metadata = metadata;
            return this;
        }

        @java.lang.Override
        public _FinalStage messages(List<ValidationMessage> messages) {
            this.messages = Optional.of(messages);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "messages", nulls = Nulls.SKIP)
        public _FinalStage messages(Optional<List<ValidationMessage>> messages) {
            this.messages = messages;
            return this;
        }

        @java.lang.Override
        public _FinalStage valid(Boolean valid) {
            this.valid = Optional.of(valid);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "valid", nulls = Nulls.SKIP)
        public _FinalStage valid(Optional<Boolean> valid) {
            this.valid = valid;
            return this;
        }

        @java.lang.Override
        public RecordWithLinks build() {
            return new RecordWithLinks(id, values, valid, messages, metadata, config, additionalProperties);
        }
    }
}
