/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flatfile.api.resources.records.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum ValidationSource {
    REQUIRED_CONSTRAINT("required-constraint"),

    UNIQUE_CONSTRAINT("unique-constraint"),

    CUSTOM_LOGIC("custom-logic"),

    UNLINKED("unlinked"),

    INVALID_OPTION("invalid-option"),

    IS_ARTIFACT("is-artifact");

    private final String value;

    ValidationSource(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
