/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flatfile.api.resources.spaces.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.flatfile.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SpaceSettings.Builder.class)
public final class SpaceSettings {
    private final Optional<SpaceSidebarConfig> sidebarConfig;

    private final Map<String, Object> additionalProperties;

    private SpaceSettings(Optional<SpaceSidebarConfig> sidebarConfig, Map<String, Object> additionalProperties) {
        this.sidebarConfig = sidebarConfig;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The sidebar configuration for the space. (This will eventually replace metadata.sidebarconfig)
     */
    @JsonProperty("sidebarConfig")
    public Optional<SpaceSidebarConfig> getSidebarConfig() {
        return sidebarConfig;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SpaceSettings && equalTo((SpaceSettings) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SpaceSettings other) {
        return sidebarConfig.equals(other.sidebarConfig);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.sidebarConfig);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<SpaceSidebarConfig> sidebarConfig = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(SpaceSettings other) {
            sidebarConfig(other.getSidebarConfig());
            return this;
        }

        @JsonSetter(value = "sidebarConfig", nulls = Nulls.SKIP)
        public Builder sidebarConfig(Optional<SpaceSidebarConfig> sidebarConfig) {
            this.sidebarConfig = sidebarConfig;
            return this;
        }

        public Builder sidebarConfig(SpaceSidebarConfig sidebarConfig) {
            this.sidebarConfig = Optional.ofNullable(sidebarConfig);
            return this;
        }

        public SpaceSettings build() {
            return new SpaceSettings(sidebarConfig, additionalProperties);
        }
    }
}
