/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flatfile.api.resources.property.types;

import java.util.List;
import java.util.Optional;

public interface IBaseProperty {
    String getKey();

    Optional<String> getLabel();

    Optional<String> getDescription();

    Optional<List<Constraint>> getConstraints();

    Optional<Boolean> getReadonly();

    Optional<FieldAppearance> getAppearance();

    Optional<Object> getMetadata();

    Optional<List<String>> getTreatments();

    Optional<List<String>> getAlternativeNames();
}
