/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flatfile.api.resources.commons.errors;

import com.flatfile.api.core.FlatfileApiException;
import com.flatfile.api.resources.commons.types.Errors;

public final class NotFoundError extends FlatfileApiException {
    /**
     * The body of the response that triggered the exception.
     */
    private final Errors body;

    public NotFoundError(Errors body) {
        super("NotFoundError", 404, body);
        this.body = body;
    }

    /**
     * @return the body
     */
    @java.lang.Override
    public Errors body() {
        return this.body;
    }
}
