/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flatfile.api.resources.commons.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum ActionSchedule {
    WEEKLY("weekly"),

    DAILY("daily"),

    HOURLY("hourly");

    private final String value;

    ActionSchedule(String value) {
        this.value = value;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
