/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flatfile.api.resources.commons.types;

import java.util.List;
import java.util.Optional;

public interface IActionWithoutLabel {
    Optional<String> getSlug();

    Optional<String> getOperation();

    Optional<ActionMode> getMode();

    Optional<String> getTooltip();

    Optional<List<ActionMessage>> getMessages();

    Optional<String> getType();

    Optional<String> getDescription();

    Optional<ActionSchedule> getSchedule();

    Optional<Boolean> getPrimary();

    Optional<Boolean> getConfirm();

    Optional<String> getIcon();

    Optional<Boolean> getRequireAllValid();

    Optional<Boolean> getRequireSelection();

    Optional<InputForm> getInputForm();

    Optional<List<ActionConstraint>> getConstraints();

    Optional<ActionMount> getMount();

    Optional<Guide> getGuide();

    Optional<Guardrail> getGuardrail();
}
