/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flatfile.api.resources.agents.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.flatfile.api.core.ObjectMappers;
import com.flatfile.api.resources.commons.types.EventId;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = Execution.Builder.class)
public final class Execution {
    private final EventId eventId;

    private final boolean success;

    private final OffsetDateTime createdAt;

    private final OffsetDateTime completedAt;

    private final int duration;

    private final String topic;

    private final Map<String, Object> additionalProperties;

    private Execution(
            EventId eventId,
            boolean success,
            OffsetDateTime createdAt,
            OffsetDateTime completedAt,
            int duration,
            String topic,
            Map<String, Object> additionalProperties) {
        this.eventId = eventId;
        this.success = success;
        this.createdAt = createdAt;
        this.completedAt = completedAt;
        this.duration = duration;
        this.topic = topic;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("eventId")
    public EventId getEventId() {
        return eventId;
    }

    /**
     * @return Whether the agent execution was successful
     */
    @JsonProperty("success")
    public boolean getSuccess() {
        return success;
    }

    @JsonProperty("createdAt")
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    @JsonProperty("completedAt")
    public OffsetDateTime getCompletedAt() {
        return completedAt;
    }

    /**
     * @return The duration of the agent execution
     */
    @JsonProperty("duration")
    public int getDuration() {
        return duration;
    }

    /**
     * @return The topics of the agent execution
     */
    @JsonProperty("topic")
    public String getTopic() {
        return topic;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof Execution && equalTo((Execution) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(Execution other) {
        return eventId.equals(other.eventId)
                && success == other.success
                && createdAt.equals(other.createdAt)
                && completedAt.equals(other.completedAt)
                && duration == other.duration
                && topic.equals(other.topic);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.eventId, this.success, this.createdAt, this.completedAt, this.duration, this.topic);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static EventIdStage builder() {
        return new Builder();
    }

    public interface EventIdStage {
        SuccessStage eventId(EventId eventId);

        Builder from(Execution other);
    }

    public interface SuccessStage {
        CreatedAtStage success(boolean success);
    }

    public interface CreatedAtStage {
        CompletedAtStage createdAt(OffsetDateTime createdAt);
    }

    public interface CompletedAtStage {
        DurationStage completedAt(OffsetDateTime completedAt);
    }

    public interface DurationStage {
        TopicStage duration(int duration);
    }

    public interface TopicStage {
        _FinalStage topic(String topic);
    }

    public interface _FinalStage {
        Execution build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements EventIdStage,
                    SuccessStage,
                    CreatedAtStage,
                    CompletedAtStage,
                    DurationStage,
                    TopicStage,
                    _FinalStage {
        private EventId eventId;

        private boolean success;

        private OffsetDateTime createdAt;

        private OffsetDateTime completedAt;

        private int duration;

        private String topic;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @Override
        public Builder from(Execution other) {
            eventId(other.getEventId());
            success(other.getSuccess());
            createdAt(other.getCreatedAt());
            completedAt(other.getCompletedAt());
            duration(other.getDuration());
            topic(other.getTopic());
            return this;
        }

        @Override
        @JsonSetter("eventId")
        public SuccessStage eventId(EventId eventId) {
            this.eventId = eventId;
            return this;
        }

        /**
         * <p>Whether the agent execution was successful</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @Override
        @JsonSetter("success")
        public CreatedAtStage success(boolean success) {
            this.success = success;
            return this;
        }

        @Override
        @JsonSetter("createdAt")
        public CompletedAtStage createdAt(OffsetDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        @Override
        @JsonSetter("completedAt")
        public DurationStage completedAt(OffsetDateTime completedAt) {
            this.completedAt = completedAt;
            return this;
        }

        /**
         * <p>The duration of the agent execution</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @Override
        @JsonSetter("duration")
        public TopicStage duration(int duration) {
            this.duration = duration;
            return this;
        }

        /**
         * <p>The topics of the agent execution</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @Override
        @JsonSetter("topic")
        public _FinalStage topic(String topic) {
            this.topic = topic;
            return this;
        }

        @Override
        public Execution build() {
            return new Execution(eventId, success, createdAt, completedAt, duration, topic, additionalProperties);
        }
    }
}
