/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flatfile.api.resources.mapping.types;

import com.flatfile.api.resources.commons.types.MappingId;
import com.flatfile.api.resources.commons.types.UserId;
import java.time.OffsetDateTime;
import java.util.Optional;

public interface IMappingRuleBase extends IMappingRuleConfig {
    MappingId getId();

    Optional<Double> getConfidence();

    Optional<UserId> getCreatedBy();

    OffsetDateTime getCreatedAt();

    OffsetDateTime getUpdatedAt();
}
