/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flatfile.api.resources.mapping.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.flatfile.api.core.ObjectMappers;
import com.flatfile.api.resources.commons.types.UserId;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = MappingRuleConfig.Builder.class)
public final class MappingRuleConfig implements IMappingRuleConfig {
    private final String name;

    private final String type;

    private final Optional<Object> config;

    private final Optional<OffsetDateTime> acceptedAt;

    private final Optional<UserId> acceptedBy;

    private final Map<String, Object> additionalProperties;

    private MappingRuleConfig(
            String name,
            String type,
            Optional<Object> config,
            Optional<OffsetDateTime> acceptedAt,
            Optional<UserId> acceptedBy,
            Map<String, Object> additionalProperties) {
        this.name = name;
        this.type = type;
        this.config = config;
        this.acceptedAt = acceptedAt;
        this.acceptedBy = acceptedBy;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Name of the mapping rule
     */
    @JsonProperty("name")
    @java.lang.Override
    public String getName() {
        return name;
    }

    @JsonProperty("type")
    @java.lang.Override
    public String getType() {
        return type;
    }

    @JsonProperty("config")
    @java.lang.Override
    public Optional<Object> getConfig() {
        return config;
    }

    /**
     * @return Time the mapping rule was last updated
     */
    @JsonProperty("acceptedAt")
    @java.lang.Override
    public Optional<OffsetDateTime> getAcceptedAt() {
        return acceptedAt;
    }

    /**
     * @return User ID of the contributor of the mapping rule
     */
    @JsonProperty("acceptedBy")
    @java.lang.Override
    public Optional<UserId> getAcceptedBy() {
        return acceptedBy;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof MappingRuleConfig && equalTo((MappingRuleConfig) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(MappingRuleConfig other) {
        return name.equals(other.name)
                && type.equals(other.type)
                && config.equals(other.config)
                && acceptedAt.equals(other.acceptedAt)
                && acceptedBy.equals(other.acceptedBy);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.name, this.type, this.config, this.acceptedAt, this.acceptedBy);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static NameStage builder() {
        return new Builder();
    }

    public interface NameStage {
        TypeStage name(String name);

        Builder from(MappingRuleConfig other);
    }

    public interface TypeStage {
        _FinalStage type(String type);
    }

    public interface _FinalStage {
        MappingRuleConfig build();

        _FinalStage config(Optional<Object> config);

        _FinalStage config(Object config);

        _FinalStage acceptedAt(Optional<OffsetDateTime> acceptedAt);

        _FinalStage acceptedAt(OffsetDateTime acceptedAt);

        _FinalStage acceptedBy(Optional<UserId> acceptedBy);

        _FinalStage acceptedBy(UserId acceptedBy);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements NameStage, TypeStage, _FinalStage {
        private String name;

        private String type;

        private Optional<UserId> acceptedBy = Optional.empty();

        private Optional<OffsetDateTime> acceptedAt = Optional.empty();

        private Optional<Object> config = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(MappingRuleConfig other) {
            name(other.getName());
            type(other.getType());
            config(other.getConfig());
            acceptedAt(other.getAcceptedAt());
            acceptedBy(other.getAcceptedBy());
            return this;
        }

        /**
         * <p>Name of the mapping rule</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public TypeStage name(String name) {
            this.name = name;
            return this;
        }

        @java.lang.Override
        @JsonSetter("type")
        public _FinalStage type(String type) {
            this.type = type;
            return this;
        }

        /**
         * <p>User ID of the contributor of the mapping rule</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage acceptedBy(UserId acceptedBy) {
            this.acceptedBy = Optional.of(acceptedBy);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "acceptedBy", nulls = Nulls.SKIP)
        public _FinalStage acceptedBy(Optional<UserId> acceptedBy) {
            this.acceptedBy = acceptedBy;
            return this;
        }

        /**
         * <p>Time the mapping rule was last updated</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage acceptedAt(OffsetDateTime acceptedAt) {
            this.acceptedAt = Optional.of(acceptedAt);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "acceptedAt", nulls = Nulls.SKIP)
        public _FinalStage acceptedAt(Optional<OffsetDateTime> acceptedAt) {
            this.acceptedAt = acceptedAt;
            return this;
        }

        @java.lang.Override
        public _FinalStage config(Object config) {
            this.config = Optional.of(config);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "config", nulls = Nulls.SKIP)
        public _FinalStage config(Optional<Object> config) {
            this.config = config;
            return this;
        }

        @java.lang.Override
        public MappingRuleConfig build() {
            return new MappingRuleConfig(name, type, config, acceptedAt, acceptedBy, additionalProperties);
        }
    }
}
