/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flatfile.api.resources.mapping.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.flatfile.api.core.ObjectMappers;
import com.flatfile.api.resources.commons.types.UserId;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = MappingRuleConfig.Builder.class)
public final class MappingRuleConfig implements IMappingRuleConfig {
    private final String name;

    private final String type;

    private final Optional<Object> config;

    private final Optional<Integer> confidence;

    private final Optional<UserId> contributor;

    private final Map<String, Object> additionalProperties;

    private MappingRuleConfig(
            String name,
            String type,
            Optional<Object> config,
            Optional<Integer> confidence,
            Optional<UserId> contributor,
            Map<String, Object> additionalProperties) {
        this.name = name;
        this.type = type;
        this.config = config;
        this.confidence = confidence;
        this.contributor = contributor;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Name of the mapping rule
     */
    @JsonProperty("name")
    @Override
    public String getName() {
        return name;
    }

    @JsonProperty("type")
    @Override
    public String getType() {
        return type;
    }

    @JsonProperty("config")
    @Override
    public Optional<Object> getConfig() {
        return config;
    }

    /**
     * @return Confidence of the mapping rule
     */
    @JsonProperty("confidence")
    @Override
    public Optional<Integer> getConfidence() {
        return confidence;
    }

    /**
     * @return User ID of the contributor of the mapping rule
     */
    @JsonProperty("contributor")
    @Override
    public Optional<UserId> getContributor() {
        return contributor;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof MappingRuleConfig && equalTo((MappingRuleConfig) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(MappingRuleConfig other) {
        return name.equals(other.name)
                && type.equals(other.type)
                && config.equals(other.config)
                && confidence.equals(other.confidence)
                && contributor.equals(other.contributor);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.name, this.type, this.config, this.confidence, this.contributor);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static NameStage builder() {
        return new Builder();
    }

    public interface NameStage {
        TypeStage name(String name);

        Builder from(MappingRuleConfig other);
    }

    public interface TypeStage {
        _FinalStage type(String type);
    }

    public interface _FinalStage {
        MappingRuleConfig build();

        _FinalStage config(Optional<Object> config);

        _FinalStage config(Object config);

        _FinalStage confidence(Optional<Integer> confidence);

        _FinalStage confidence(Integer confidence);

        _FinalStage contributor(Optional<UserId> contributor);

        _FinalStage contributor(UserId contributor);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements NameStage, TypeStage, _FinalStage {
        private String name;

        private String type;

        private Optional<UserId> contributor = Optional.empty();

        private Optional<Integer> confidence = Optional.empty();

        private Optional<Object> config = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @Override
        public Builder from(MappingRuleConfig other) {
            name(other.getName());
            type(other.getType());
            config(other.getConfig());
            confidence(other.getConfidence());
            contributor(other.getContributor());
            return this;
        }

        /**
         * <p>Name of the mapping rule</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @Override
        @JsonSetter("name")
        public TypeStage name(String name) {
            this.name = name;
            return this;
        }

        @Override
        @JsonSetter("type")
        public _FinalStage type(String type) {
            this.type = type;
            return this;
        }

        /**
         * <p>User ID of the contributor of the mapping rule</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @Override
        public _FinalStage contributor(UserId contributor) {
            this.contributor = Optional.of(contributor);
            return this;
        }

        @Override
        @JsonSetter(value = "contributor", nulls = Nulls.SKIP)
        public _FinalStage contributor(Optional<UserId> contributor) {
            this.contributor = contributor;
            return this;
        }

        /**
         * <p>Confidence of the mapping rule</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @Override
        public _FinalStage confidence(Integer confidence) {
            this.confidence = Optional.of(confidence);
            return this;
        }

        @Override
        @JsonSetter(value = "confidence", nulls = Nulls.SKIP)
        public _FinalStage confidence(Optional<Integer> confidence) {
            this.confidence = confidence;
            return this;
        }

        @Override
        public _FinalStage config(Object config) {
            this.config = Optional.of(config);
            return this;
        }

        @Override
        @JsonSetter(value = "config", nulls = Nulls.SKIP)
        public _FinalStage config(Optional<Object> config) {
            this.config = config;
            return this;
        }

        @Override
        public MappingRuleConfig build() {
            return new MappingRuleConfig(name, type, config, confidence, contributor, additionalProperties);
        }
    }
}
