/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flatfile.api.resources.mapping.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.List;

public final class UpdateMappingRulesRequest {
    private final List<MappingRule> value;

    private UpdateMappingRulesRequest(List<MappingRule> value) {
        this.value = value;
    }

    @JsonValue
    public List<MappingRule> get() {
        return this.value;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return this == other
                || (other instanceof UpdateMappingRulesRequest
                        && this.value.equals(((UpdateMappingRulesRequest) other).value));
    }

    @java.lang.Override
    public int hashCode() {
        return value.hashCode();
    }

    @java.lang.Override
    public String toString() {
        return value.toString();
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static UpdateMappingRulesRequest of(List<MappingRule> value) {
        return new UpdateMappingRulesRequest(value);
    }
}
