/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flatfile.api.resources.events.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.flatfile.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateEventConfig.Builder.class)
public final class CreateEventConfig implements IBaseEvent {
    private final Domain domain;

    private final Context context;

    private final Optional<EventAttributes> attributes;

    private final Optional<String> callbackUrl;

    private final Optional<String> dataUrl;

    private final Optional<String> target;

    private final Optional<Origin> origin;

    private final Optional<List<String>> namespaces;

    private final EventTopic topic;

    private final Map<String, Object> payload;

    private final Optional<OffsetDateTime> deletedAt;

    private final Map<String, Object> additionalProperties;

    private CreateEventConfig(
            Domain domain,
            Context context,
            Optional<EventAttributes> attributes,
            Optional<String> callbackUrl,
            Optional<String> dataUrl,
            Optional<String> target,
            Optional<Origin> origin,
            Optional<List<String>> namespaces,
            EventTopic topic,
            Map<String, Object> payload,
            Optional<OffsetDateTime> deletedAt,
            Map<String, Object> additionalProperties) {
        this.domain = domain;
        this.context = context;
        this.attributes = attributes;
        this.callbackUrl = callbackUrl;
        this.dataUrl = dataUrl;
        this.target = target;
        this.origin = origin;
        this.namespaces = namespaces;
        this.topic = topic;
        this.payload = payload;
        this.deletedAt = deletedAt;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The domain of the event
     */
    @JsonProperty("domain")
    @java.lang.Override
    public Domain getDomain() {
        return domain;
    }

    /**
     * @return The context of the event
     */
    @JsonProperty("context")
    @java.lang.Override
    public Context getContext() {
        return context;
    }

    /**
     * @return The attributes of the event
     */
    @JsonProperty("attributes")
    @java.lang.Override
    public Optional<EventAttributes> getAttributes() {
        return attributes;
    }

    /**
     * @return The callback url to acknowledge the event
     */
    @JsonProperty("callbackUrl")
    @java.lang.Override
    public Optional<String> getCallbackUrl() {
        return callbackUrl;
    }

    /**
     * @return The url to retrieve the data associated with the event
     */
    @JsonProperty("dataUrl")
    @java.lang.Override
    public Optional<String> getDataUrl() {
        return dataUrl;
    }

    @JsonProperty("target")
    @java.lang.Override
    public Optional<String> getTarget() {
        return target;
    }

    @JsonProperty("origin")
    @java.lang.Override
    public Optional<Origin> getOrigin() {
        return origin;
    }

    @JsonProperty("namespaces")
    @java.lang.Override
    public Optional<List<String>> getNamespaces() {
        return namespaces;
    }

    @JsonProperty("topic")
    public EventTopic getTopic() {
        return topic;
    }

    @JsonProperty("payload")
    public Map<String, Object> getPayload() {
        return payload;
    }

    /**
     * @return Date the event was deleted
     */
    @JsonProperty("deletedAt")
    public Optional<OffsetDateTime> getDeletedAt() {
        return deletedAt;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateEventConfig && equalTo((CreateEventConfig) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateEventConfig other) {
        return domain.equals(other.domain)
                && context.equals(other.context)
                && attributes.equals(other.attributes)
                && callbackUrl.equals(other.callbackUrl)
                && dataUrl.equals(other.dataUrl)
                && target.equals(other.target)
                && origin.equals(other.origin)
                && namespaces.equals(other.namespaces)
                && topic.equals(other.topic)
                && payload.equals(other.payload)
                && deletedAt.equals(other.deletedAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.domain,
                this.context,
                this.attributes,
                this.callbackUrl,
                this.dataUrl,
                this.target,
                this.origin,
                this.namespaces,
                this.topic,
                this.payload,
                this.deletedAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static DomainStage builder() {
        return new Builder();
    }

    public interface DomainStage {
        ContextStage domain(@NotNull Domain domain);

        Builder from(CreateEventConfig other);
    }

    public interface ContextStage {
        TopicStage context(@NotNull Context context);
    }

    public interface TopicStage {
        _FinalStage topic(@NotNull EventTopic topic);
    }

    public interface _FinalStage {
        CreateEventConfig build();

        _FinalStage attributes(Optional<EventAttributes> attributes);

        _FinalStage attributes(EventAttributes attributes);

        _FinalStage callbackUrl(Optional<String> callbackUrl);

        _FinalStage callbackUrl(String callbackUrl);

        _FinalStage dataUrl(Optional<String> dataUrl);

        _FinalStage dataUrl(String dataUrl);

        _FinalStage target(Optional<String> target);

        _FinalStage target(String target);

        _FinalStage origin(Optional<Origin> origin);

        _FinalStage origin(Origin origin);

        _FinalStage namespaces(Optional<List<String>> namespaces);

        _FinalStage namespaces(List<String> namespaces);

        _FinalStage payload(Map<String, Object> payload);

        _FinalStage putAllPayload(Map<String, Object> payload);

        _FinalStage payload(String key, Object value);

        _FinalStage deletedAt(Optional<OffsetDateTime> deletedAt);

        _FinalStage deletedAt(OffsetDateTime deletedAt);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements DomainStage, ContextStage, TopicStage, _FinalStage {
        private Domain domain;

        private Context context;

        private EventTopic topic;

        private Optional<OffsetDateTime> deletedAt = Optional.empty();

        private Map<String, Object> payload = new LinkedHashMap<>();

        private Optional<List<String>> namespaces = Optional.empty();

        private Optional<Origin> origin = Optional.empty();

        private Optional<String> target = Optional.empty();

        private Optional<String> dataUrl = Optional.empty();

        private Optional<String> callbackUrl = Optional.empty();

        private Optional<EventAttributes> attributes = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CreateEventConfig other) {
            domain(other.getDomain());
            context(other.getContext());
            attributes(other.getAttributes());
            callbackUrl(other.getCallbackUrl());
            dataUrl(other.getDataUrl());
            target(other.getTarget());
            origin(other.getOrigin());
            namespaces(other.getNamespaces());
            topic(other.getTopic());
            payload(other.getPayload());
            deletedAt(other.getDeletedAt());
            return this;
        }

        /**
         * <p>The domain of the event</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("domain")
        public ContextStage domain(@NotNull Domain domain) {
            this.domain = Objects.requireNonNull(domain, "domain must not be null");
            return this;
        }

        /**
         * <p>The context of the event</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("context")
        public TopicStage context(@NotNull Context context) {
            this.context = Objects.requireNonNull(context, "context must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("topic")
        public _FinalStage topic(@NotNull EventTopic topic) {
            this.topic = Objects.requireNonNull(topic, "topic must not be null");
            return this;
        }

        /**
         * <p>Date the event was deleted</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage deletedAt(OffsetDateTime deletedAt) {
            this.deletedAt = Optional.ofNullable(deletedAt);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "deletedAt", nulls = Nulls.SKIP)
        public _FinalStage deletedAt(Optional<OffsetDateTime> deletedAt) {
            this.deletedAt = deletedAt;
            return this;
        }

        @java.lang.Override
        public _FinalStage payload(String key, Object value) {
            this.payload.put(key, value);
            return this;
        }

        @java.lang.Override
        public _FinalStage putAllPayload(Map<String, Object> payload) {
            this.payload.putAll(payload);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "payload", nulls = Nulls.SKIP)
        public _FinalStage payload(Map<String, Object> payload) {
            this.payload.clear();
            this.payload.putAll(payload);
            return this;
        }

        @java.lang.Override
        public _FinalStage namespaces(List<String> namespaces) {
            this.namespaces = Optional.ofNullable(namespaces);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "namespaces", nulls = Nulls.SKIP)
        public _FinalStage namespaces(Optional<List<String>> namespaces) {
            this.namespaces = namespaces;
            return this;
        }

        @java.lang.Override
        public _FinalStage origin(Origin origin) {
            this.origin = Optional.ofNullable(origin);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "origin", nulls = Nulls.SKIP)
        public _FinalStage origin(Optional<Origin> origin) {
            this.origin = origin;
            return this;
        }

        @java.lang.Override
        public _FinalStage target(String target) {
            this.target = Optional.ofNullable(target);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "target", nulls = Nulls.SKIP)
        public _FinalStage target(Optional<String> target) {
            this.target = target;
            return this;
        }

        /**
         * <p>The url to retrieve the data associated with the event</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage dataUrl(String dataUrl) {
            this.dataUrl = Optional.ofNullable(dataUrl);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "dataUrl", nulls = Nulls.SKIP)
        public _FinalStage dataUrl(Optional<String> dataUrl) {
            this.dataUrl = dataUrl;
            return this;
        }

        /**
         * <p>The callback url to acknowledge the event</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage callbackUrl(String callbackUrl) {
            this.callbackUrl = Optional.ofNullable(callbackUrl);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "callbackUrl", nulls = Nulls.SKIP)
        public _FinalStage callbackUrl(Optional<String> callbackUrl) {
            this.callbackUrl = callbackUrl;
            return this;
        }

        /**
         * <p>The attributes of the event</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage attributes(EventAttributes attributes) {
            this.attributes = Optional.ofNullable(attributes);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "attributes", nulls = Nulls.SKIP)
        public _FinalStage attributes(Optional<EventAttributes> attributes) {
            this.attributes = attributes;
            return this;
        }

        @java.lang.Override
        public CreateEventConfig build() {
            return new CreateEventConfig(
                    domain,
                    context,
                    attributes,
                    callbackUrl,
                    dataUrl,
                    target,
                    origin,
                    namespaces,
                    topic,
                    payload,
                    deletedAt,
                    additionalProperties);
        }
    }
}
