/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flatfile.api.resources.secrets.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.flatfile.api.core.ObjectMappers;
import com.flatfile.api.resources.commons.types.EnvironmentId;
import com.flatfile.api.resources.commons.types.SpaceId;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = ListSecrets.Builder.class)
public final class ListSecrets {
    private final EnvironmentId environmentId;

    private final Optional<SpaceId> spaceId;

    private final Map<String, Object> additionalProperties;

    private ListSecrets(
            EnvironmentId environmentId, Optional<SpaceId> spaceId, Map<String, Object> additionalProperties) {
        this.environmentId = environmentId;
        this.spaceId = spaceId;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The Environment of the secret.
     */
    @JsonProperty("environmentId")
    public EnvironmentId getEnvironmentId() {
        return environmentId;
    }

    /**
     * @return The Space of the secret.
     */
    @JsonProperty("spaceId")
    public Optional<SpaceId> getSpaceId() {
        return spaceId;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListSecrets && equalTo((ListSecrets) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListSecrets other) {
        return environmentId.equals(other.environmentId) && spaceId.equals(other.spaceId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.environmentId, this.spaceId);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static EnvironmentIdStage builder() {
        return new Builder();
    }

    public interface EnvironmentIdStage {
        _FinalStage environmentId(EnvironmentId environmentId);

        Builder from(ListSecrets other);
    }

    public interface _FinalStage {
        ListSecrets build();

        _FinalStage spaceId(Optional<SpaceId> spaceId);

        _FinalStage spaceId(SpaceId spaceId);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements EnvironmentIdStage, _FinalStage {
        private EnvironmentId environmentId;

        private Optional<SpaceId> spaceId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @Override
        public Builder from(ListSecrets other) {
            environmentId(other.getEnvironmentId());
            spaceId(other.getSpaceId());
            return this;
        }

        /**
         * <p>The Environment of the secret.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @Override
        @JsonSetter("environmentId")
        public _FinalStage environmentId(EnvironmentId environmentId) {
            this.environmentId = environmentId;
            return this;
        }

        /**
         * <p>The Space of the secret.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @Override
        public _FinalStage spaceId(SpaceId spaceId) {
            this.spaceId = Optional.of(spaceId);
            return this;
        }

        @Override
        @JsonSetter(value = "spaceId", nulls = Nulls.SKIP)
        public _FinalStage spaceId(Optional<SpaceId> spaceId) {
            this.spaceId = spaceId;
            return this;
        }

        @Override
        public ListSecrets build() {
            return new ListSecrets(environmentId, spaceId, additionalProperties);
        }
    }
}
