/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flatfile.api;

import com.flatfile.api.core.ClientOptions;
import com.flatfile.api.core.Suppliers;
import com.flatfile.api.resources.accounts.AccountsClient;
import com.flatfile.api.resources.agents.AgentsClient;
import com.flatfile.api.resources.apps.AppsClient;
import com.flatfile.api.resources.assistant.AssistantClient;
import com.flatfile.api.resources.commits.CommitsClient;
import com.flatfile.api.resources.dataretentionpolicies.DataRetentionPoliciesClient;
import com.flatfile.api.resources.documents.DocumentsClient;
import com.flatfile.api.resources.entitlements.EntitlementsClient;
import com.flatfile.api.resources.environments.EnvironmentsClient;
import com.flatfile.api.resources.events.EventsClient;
import com.flatfile.api.resources.files.FilesClient;
import com.flatfile.api.resources.guests.GuestsClient;
import com.flatfile.api.resources.jobs.JobsClient;
import com.flatfile.api.resources.mapping.MappingClient;
import com.flatfile.api.resources.records.RecordsClient;
import com.flatfile.api.resources.roles.RolesClient;
import com.flatfile.api.resources.secrets.SecretsClient;
import com.flatfile.api.resources.sheets.SheetsClient;
import com.flatfile.api.resources.snapshots.SnapshotsClient;
import com.flatfile.api.resources.spaces.SpacesClient;
import com.flatfile.api.resources.users.UsersClient;
import com.flatfile.api.resources.versions.VersionsClient;
import com.flatfile.api.resources.views.ViewsClient;
import com.flatfile.api.resources.workbooks.WorkbooksClient;
import java.util.function.Supplier;

public class Flatfile {
    protected final ClientOptions clientOptions;

    protected final Supplier<AccountsClient> accountsClient;

    protected final Supplier<AgentsClient> agentsClient;

    protected final Supplier<AppsClient> appsClient;

    protected final Supplier<AssistantClient> assistantClient;

    protected final Supplier<CommitsClient> commitsClient;

    protected final Supplier<DataRetentionPoliciesClient> dataRetentionPoliciesClient;

    protected final Supplier<DocumentsClient> documentsClient;

    protected final Supplier<EntitlementsClient> entitlementsClient;

    protected final Supplier<EnvironmentsClient> environmentsClient;

    protected final Supplier<EventsClient> eventsClient;

    protected final Supplier<FilesClient> filesClient;

    protected final Supplier<GuestsClient> guestsClient;

    protected final Supplier<JobsClient> jobsClient;

    protected final Supplier<MappingClient> mappingClient;

    protected final Supplier<RecordsClient> recordsClient;

    protected final Supplier<RolesClient> rolesClient;

    protected final Supplier<SecretsClient> secretsClient;

    protected final Supplier<SheetsClient> sheetsClient;

    protected final Supplier<SnapshotsClient> snapshotsClient;

    protected final Supplier<SpacesClient> spacesClient;

    protected final Supplier<UsersClient> usersClient;

    protected final Supplier<VersionsClient> versionsClient;

    protected final Supplier<ViewsClient> viewsClient;

    protected final Supplier<WorkbooksClient> workbooksClient;

    public Flatfile(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.accountsClient = Suppliers.memoize(() -> new AccountsClient(clientOptions));
        this.agentsClient = Suppliers.memoize(() -> new AgentsClient(clientOptions));
        this.appsClient = Suppliers.memoize(() -> new AppsClient(clientOptions));
        this.assistantClient = Suppliers.memoize(() -> new AssistantClient(clientOptions));
        this.commitsClient = Suppliers.memoize(() -> new CommitsClient(clientOptions));
        this.dataRetentionPoliciesClient = Suppliers.memoize(() -> new DataRetentionPoliciesClient(clientOptions));
        this.documentsClient = Suppliers.memoize(() -> new DocumentsClient(clientOptions));
        this.entitlementsClient = Suppliers.memoize(() -> new EntitlementsClient(clientOptions));
        this.environmentsClient = Suppliers.memoize(() -> new EnvironmentsClient(clientOptions));
        this.eventsClient = Suppliers.memoize(() -> new EventsClient(clientOptions));
        this.filesClient = Suppliers.memoize(() -> new FilesClient(clientOptions));
        this.guestsClient = Suppliers.memoize(() -> new GuestsClient(clientOptions));
        this.jobsClient = Suppliers.memoize(() -> new JobsClient(clientOptions));
        this.mappingClient = Suppliers.memoize(() -> new MappingClient(clientOptions));
        this.recordsClient = Suppliers.memoize(() -> new RecordsClient(clientOptions));
        this.rolesClient = Suppliers.memoize(() -> new RolesClient(clientOptions));
        this.secretsClient = Suppliers.memoize(() -> new SecretsClient(clientOptions));
        this.sheetsClient = Suppliers.memoize(() -> new SheetsClient(clientOptions));
        this.snapshotsClient = Suppliers.memoize(() -> new SnapshotsClient(clientOptions));
        this.spacesClient = Suppliers.memoize(() -> new SpacesClient(clientOptions));
        this.usersClient = Suppliers.memoize(() -> new UsersClient(clientOptions));
        this.versionsClient = Suppliers.memoize(() -> new VersionsClient(clientOptions));
        this.viewsClient = Suppliers.memoize(() -> new ViewsClient(clientOptions));
        this.workbooksClient = Suppliers.memoize(() -> new WorkbooksClient(clientOptions));
    }

    public AccountsClient accounts() {
        return this.accountsClient.get();
    }

    public AgentsClient agents() {
        return this.agentsClient.get();
    }

    public AppsClient apps() {
        return this.appsClient.get();
    }

    public AssistantClient assistant() {
        return this.assistantClient.get();
    }

    public CommitsClient commits() {
        return this.commitsClient.get();
    }

    public DataRetentionPoliciesClient dataRetentionPolicies() {
        return this.dataRetentionPoliciesClient.get();
    }

    public DocumentsClient documents() {
        return this.documentsClient.get();
    }

    public EntitlementsClient entitlements() {
        return this.entitlementsClient.get();
    }

    public EnvironmentsClient environments() {
        return this.environmentsClient.get();
    }

    public EventsClient events() {
        return this.eventsClient.get();
    }

    public FilesClient files() {
        return this.filesClient.get();
    }

    public GuestsClient guests() {
        return this.guestsClient.get();
    }

    public JobsClient jobs() {
        return this.jobsClient.get();
    }

    public MappingClient mapping() {
        return this.mappingClient.get();
    }

    public RecordsClient records() {
        return this.recordsClient.get();
    }

    public RolesClient roles() {
        return this.rolesClient.get();
    }

    public SecretsClient secrets() {
        return this.secretsClient.get();
    }

    public SheetsClient sheets() {
        return this.sheetsClient.get();
    }

    public SnapshotsClient snapshots() {
        return this.snapshotsClient.get();
    }

    public SpacesClient spaces() {
        return this.spacesClient.get();
    }

    public UsersClient users() {
        return this.usersClient.get();
    }

    public VersionsClient versions() {
        return this.versionsClient.get();
    }

    public ViewsClient views() {
        return this.viewsClient.get();
    }

    public WorkbooksClient workbooks() {
        return this.workbooksClient.get();
    }

    public static FlatfileBuilder builder() {
        return new FlatfileBuilder();
    }
}
