/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flatfile.api.resources.sheets.types;

import com.flatfile.api.resources.commons.types.SheetId;
import com.flatfile.api.resources.commons.types.WorkbookId;
import java.time.OffsetDateTime;
import java.util.Optional;

public interface ISheetUpdate {
    Optional<SheetId> getId();

    Optional<WorkbookId> getWorkbookId();

    Optional<SheetConfig> getConfig();

    Optional<String> getNamespace();

    Optional<OffsetDateTime> getUpdatedAt();

    Optional<OffsetDateTime> getCreatedAt();
}
