/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flatfile.api.resources.roles.types;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.flatfile.api.core.ObjectMappers;
import com.flatfile.api.resources.commons.types.AgentId;
import com.flatfile.api.resources.commons.types.GuestId;
import com.flatfile.api.resources.commons.types.UserId;
import java.io.IOException;
import java.util.Objects;

@JsonDeserialize(using = ActorIdUnion.Deserializer.class)
public final class ActorIdUnion {
    private final Object value;

    private final int type;

    private ActorIdUnion(Object value, int type) {
        this.value = value;
        this.type = type;
    }

    @JsonValue
    public Object get() {
        return this.value;
    }

    public <T> T visit(Visitor<T> visitor) {
        if (this.type == 0) {
            return visitor.visit((UserId) this.value);
        } else if (this.type == 1) {
            return visitor.visit((AgentId) this.value);
        } else if (this.type == 2) {
            return visitor.visit((GuestId) this.value);
        }
        throw new IllegalStateException("Failed to visit value. This should never happen.");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ActorIdUnion && equalTo((ActorIdUnion) other);
    }

    private boolean equalTo(ActorIdUnion other) {
        return value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.value);
    }

    @java.lang.Override
    public String toString() {
        return this.value.toString();
    }

    public static ActorIdUnion of(UserId value) {
        return new ActorIdUnion(value, 0);
    }

    public static ActorIdUnion of(AgentId value) {
        return new ActorIdUnion(value, 1);
    }

    public static ActorIdUnion of(GuestId value) {
        return new ActorIdUnion(value, 2);
    }

    public interface Visitor<T> {
        T visit(UserId value);

        T visit(AgentId value);

        T visit(GuestId value);
    }

    static final class Deserializer extends StdDeserializer<ActorIdUnion> {
        Deserializer() {
            super(ActorIdUnion.class);
        }

        @java.lang.Override
        public ActorIdUnion deserialize(JsonParser p, DeserializationContext ctxt) throws IOException {
            Object value = p.readValueAs(Object.class);
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, UserId.class));
            } catch (IllegalArgumentException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, AgentId.class));
            } catch (IllegalArgumentException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, GuestId.class));
            } catch (IllegalArgumentException e) {
            }
            throw new JsonParseException(p, "Failed to deserialize");
        }
    }
}
