/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flatfile.api.resources.roles.types;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.flatfile.api.core.ObjectMappers;
import com.flatfile.api.resources.commons.types.AccountId;
import com.flatfile.api.resources.commons.types.EnvironmentId;
import com.flatfile.api.resources.commons.types.SpaceId;
import java.io.IOException;
import java.util.Objects;

@JsonDeserialize(using = ResourceIdUnion.Deserializer.class)
public final class ResourceIdUnion {
    private final Object value;

    private final int type;

    private ResourceIdUnion(Object value, int type) {
        this.value = value;
        this.type = type;
    }

    @JsonValue
    public Object get() {
        return this.value;
    }

    public <T> T visit(Visitor<T> visitor) {
        if (this.type == 0) {
            return visitor.visit((AccountId) this.value);
        } else if (this.type == 1) {
            return visitor.visit((EnvironmentId) this.value);
        } else if (this.type == 2) {
            return visitor.visit((SpaceId) this.value);
        }
        throw new IllegalStateException("Failed to visit value. This should never happen.");
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ResourceIdUnion && equalTo((ResourceIdUnion) other);
    }

    private boolean equalTo(ResourceIdUnion other) {
        return value.equals(other.value);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.value);
    }

    @Override
    public String toString() {
        return this.value.toString();
    }

    public static ResourceIdUnion of(AccountId value) {
        return new ResourceIdUnion(value, 0);
    }

    public static ResourceIdUnion of(EnvironmentId value) {
        return new ResourceIdUnion(value, 1);
    }

    public static ResourceIdUnion of(SpaceId value) {
        return new ResourceIdUnion(value, 2);
    }

    public interface Visitor<T> {
        T visit(AccountId value);

        T visit(EnvironmentId value);

        T visit(SpaceId value);
    }

    static final class Deserializer extends StdDeserializer<ResourceIdUnion> {
        Deserializer() {
            super(ResourceIdUnion.class);
        }

        @Override
        public ResourceIdUnion deserialize(JsonParser p, DeserializationContext ctxt) throws IOException {
            Object value = p.readValueAs(Object.class);
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, AccountId.class));
            } catch (IllegalArgumentException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, EnvironmentId.class));
            } catch (IllegalArgumentException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, SpaceId.class));
            } catch (IllegalArgumentException e) {
            }
            throw new JsonParseException(p, "Failed to deserialize");
        }
    }
}
