/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flatfile.api.resources.jobs.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.flatfile.api.core.ObjectMappers;
import com.flatfile.api.resources.commons.types.Filter;
import com.flatfile.api.resources.records.types.CellValueUnion;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = FindAndReplaceJobConfig.Builder.class)
public final class FindAndReplaceJobConfig {
    private final Optional<Filter> filter;

    private final Optional<String> filterField;

    private final Optional<String> searchValue;

    private final Optional<String> searchField;

    private final Optional<String> q;

    private final Optional<List<String>> ids;

    private final Optional<CellValueUnion> find;

    private final Optional<CellValueUnion> replace;

    private final String fieldKey;

    private final Map<String, Object> additionalProperties;

    private FindAndReplaceJobConfig(
            Optional<Filter> filter,
            Optional<String> filterField,
            Optional<String> searchValue,
            Optional<String> searchField,
            Optional<String> q,
            Optional<List<String>> ids,
            Optional<CellValueUnion> find,
            Optional<CellValueUnion> replace,
            String fieldKey,
            Map<String, Object> additionalProperties) {
        this.filter = filter;
        this.filterField = filterField;
        this.searchValue = searchValue;
        this.searchField = searchField;
        this.q = q;
        this.ids = ids;
        this.find = find;
        this.replace = replace;
        this.fieldKey = fieldKey;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("filter")
    public Optional<Filter> getFilter() {
        return filter;
    }

    @JsonProperty("filterField")
    public Optional<String> getFilterField() {
        return filterField;
    }

    @JsonProperty("searchValue")
    public Optional<String> getSearchValue() {
        return searchValue;
    }

    @JsonProperty("searchField")
    public Optional<String> getSearchField() {
        return searchField;
    }

    @JsonProperty("q")
    public Optional<String> getQ() {
        return q;
    }

    /**
     * @return The Record Ids param (ids) is a list of record ids that can be passed to several record endpoints allowing the user to identify specific records to INCLUDE in the query, or specific records to EXCLUDE, depending on whether or not filters are being applied. When passing a query param that filters the record dataset, such as 'searchValue', or a 'filter' of 'valid' | 'error' | 'all', the 'ids' param will EXCLUDE those records from the filtered results. For basic queries that do not filter the dataset, passing record ids in the 'ids' param will limit the dataset to INCLUDE just those specific records
     */
    @JsonProperty("ids")
    public Optional<List<String>> getIds() {
        return ids;
    }

    /**
     * @return A value to find for a given field in a sheet. Wrap the value in &quot;&quot; for exact match
     */
    @JsonProperty("find")
    public Optional<CellValueUnion> getFind() {
        return find;
    }

    /**
     * @return The value to replace found values with
     */
    @JsonProperty("replace")
    public Optional<CellValueUnion> getReplace() {
        return replace;
    }

    /**
     * @return A unique key used to identify a field in a sheet
     */
    @JsonProperty("fieldKey")
    public String getFieldKey() {
        return fieldKey;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof FindAndReplaceJobConfig && equalTo((FindAndReplaceJobConfig) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(FindAndReplaceJobConfig other) {
        return filter.equals(other.filter)
                && filterField.equals(other.filterField)
                && searchValue.equals(other.searchValue)
                && searchField.equals(other.searchField)
                && q.equals(other.q)
                && ids.equals(other.ids)
                && find.equals(other.find)
                && replace.equals(other.replace)
                && fieldKey.equals(other.fieldKey);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                this.filter,
                this.filterField,
                this.searchValue,
                this.searchField,
                this.q,
                this.ids,
                this.find,
                this.replace,
                this.fieldKey);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static FieldKeyStage builder() {
        return new Builder();
    }

    public interface FieldKeyStage {
        _FinalStage fieldKey(String fieldKey);

        Builder from(FindAndReplaceJobConfig other);
    }

    public interface _FinalStage {
        FindAndReplaceJobConfig build();

        _FinalStage filter(Optional<Filter> filter);

        _FinalStage filter(Filter filter);

        _FinalStage filterField(Optional<String> filterField);

        _FinalStage filterField(String filterField);

        _FinalStage searchValue(Optional<String> searchValue);

        _FinalStage searchValue(String searchValue);

        _FinalStage searchField(Optional<String> searchField);

        _FinalStage searchField(String searchField);

        _FinalStage q(Optional<String> q);

        _FinalStage q(String q);

        _FinalStage ids(Optional<List<String>> ids);

        _FinalStage ids(List<String> ids);

        _FinalStage find(Optional<CellValueUnion> find);

        _FinalStage find(CellValueUnion find);

        _FinalStage replace(Optional<CellValueUnion> replace);

        _FinalStage replace(CellValueUnion replace);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements FieldKeyStage, _FinalStage {
        private String fieldKey;

        private Optional<CellValueUnion> replace = Optional.empty();

        private Optional<CellValueUnion> find = Optional.empty();

        private Optional<List<String>> ids = Optional.empty();

        private Optional<String> q = Optional.empty();

        private Optional<String> searchField = Optional.empty();

        private Optional<String> searchValue = Optional.empty();

        private Optional<String> filterField = Optional.empty();

        private Optional<Filter> filter = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @Override
        public Builder from(FindAndReplaceJobConfig other) {
            filter(other.getFilter());
            filterField(other.getFilterField());
            searchValue(other.getSearchValue());
            searchField(other.getSearchField());
            q(other.getQ());
            ids(other.getIds());
            find(other.getFind());
            replace(other.getReplace());
            fieldKey(other.getFieldKey());
            return this;
        }

        /**
         * <p>A unique key used to identify a field in a sheet</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @Override
        @JsonSetter("fieldKey")
        public _FinalStage fieldKey(String fieldKey) {
            this.fieldKey = fieldKey;
            return this;
        }

        /**
         * <p>The value to replace found values with</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @Override
        public _FinalStage replace(CellValueUnion replace) {
            this.replace = Optional.of(replace);
            return this;
        }

        @Override
        @JsonSetter(value = "replace", nulls = Nulls.SKIP)
        public _FinalStage replace(Optional<CellValueUnion> replace) {
            this.replace = replace;
            return this;
        }

        /**
         * <p>A value to find for a given field in a sheet. Wrap the value in &quot;&quot; for exact match</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @Override
        public _FinalStage find(CellValueUnion find) {
            this.find = Optional.of(find);
            return this;
        }

        @Override
        @JsonSetter(value = "find", nulls = Nulls.SKIP)
        public _FinalStage find(Optional<CellValueUnion> find) {
            this.find = find;
            return this;
        }

        /**
         * <p>The Record Ids param (ids) is a list of record ids that can be passed to several record endpoints allowing the user to identify specific records to INCLUDE in the query, or specific records to EXCLUDE, depending on whether or not filters are being applied. When passing a query param that filters the record dataset, such as 'searchValue', or a 'filter' of 'valid' | 'error' | 'all', the 'ids' param will EXCLUDE those records from the filtered results. For basic queries that do not filter the dataset, passing record ids in the 'ids' param will limit the dataset to INCLUDE just those specific records</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @Override
        public _FinalStage ids(List<String> ids) {
            this.ids = Optional.of(ids);
            return this;
        }

        @Override
        @JsonSetter(value = "ids", nulls = Nulls.SKIP)
        public _FinalStage ids(Optional<List<String>> ids) {
            this.ids = ids;
            return this;
        }

        @Override
        public _FinalStage q(String q) {
            this.q = Optional.of(q);
            return this;
        }

        @Override
        @JsonSetter(value = "q", nulls = Nulls.SKIP)
        public _FinalStage q(Optional<String> q) {
            this.q = q;
            return this;
        }

        @Override
        public _FinalStage searchField(String searchField) {
            this.searchField = Optional.of(searchField);
            return this;
        }

        @Override
        @JsonSetter(value = "searchField", nulls = Nulls.SKIP)
        public _FinalStage searchField(Optional<String> searchField) {
            this.searchField = searchField;
            return this;
        }

        @Override
        public _FinalStage searchValue(String searchValue) {
            this.searchValue = Optional.of(searchValue);
            return this;
        }

        @Override
        @JsonSetter(value = "searchValue", nulls = Nulls.SKIP)
        public _FinalStage searchValue(Optional<String> searchValue) {
            this.searchValue = searchValue;
            return this;
        }

        @Override
        public _FinalStage filterField(String filterField) {
            this.filterField = Optional.of(filterField);
            return this;
        }

        @Override
        @JsonSetter(value = "filterField", nulls = Nulls.SKIP)
        public _FinalStage filterField(Optional<String> filterField) {
            this.filterField = filterField;
            return this;
        }

        @Override
        public _FinalStage filter(Filter filter) {
            this.filter = Optional.of(filter);
            return this;
        }

        @Override
        @JsonSetter(value = "filter", nulls = Nulls.SKIP)
        public _FinalStage filter(Optional<Filter> filter) {
            this.filter = filter;
            return this;
        }

        @Override
        public FindAndReplaceJobConfig build() {
            return new FindAndReplaceJobConfig(
                    filter,
                    filterField,
                    searchValue,
                    searchField,
                    q,
                    ids,
                    find,
                    replace,
                    fieldKey,
                    additionalProperties);
        }
    }
}
