/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flatfile.api.resources.jobs.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.flatfile.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = JobCompleteDetails.Builder.class)
public final class JobCompleteDetails {
    private final Optional<JobOutcome> outcome;

    private final Optional<String> info;

    private final Map<String, Object> additionalProperties;

    private JobCompleteDetails(
            Optional<JobOutcome> outcome, Optional<String> info, Map<String, Object> additionalProperties) {
        this.outcome = outcome;
        this.info = info;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("outcome")
    public Optional<JobOutcome> getOutcome() {
        return outcome;
    }

    @JsonProperty("info")
    public Optional<String> getInfo() {
        return info;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof JobCompleteDetails && equalTo((JobCompleteDetails) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(JobCompleteDetails other) {
        return outcome.equals(other.outcome) && info.equals(other.info);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.outcome, this.info);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<JobOutcome> outcome = Optional.empty();

        private Optional<String> info = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(JobCompleteDetails other) {
            outcome(other.getOutcome());
            info(other.getInfo());
            return this;
        }

        @JsonSetter(value = "outcome", nulls = Nulls.SKIP)
        public Builder outcome(Optional<JobOutcome> outcome) {
            this.outcome = outcome;
            return this;
        }

        public Builder outcome(JobOutcome outcome) {
            this.outcome = Optional.of(outcome);
            return this;
        }

        @JsonSetter(value = "info", nulls = Nulls.SKIP)
        public Builder info(Optional<String> info) {
            this.info = info;
            return this;
        }

        public Builder info(String info) {
            this.info = Optional.of(info);
            return this;
        }

        public JobCompleteDetails build() {
            return new JobCompleteDetails(outcome, info, additionalProperties);
        }
    }
}
