/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flatfile.api.resources.jobs.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.flatfile.api.resources.commons.types.WorkbookId;

public final class JobDestination {
    private final WorkbookId value;

    private JobDestination(WorkbookId value) {
        this.value = value;
    }

    @JsonValue
    public WorkbookId get() {
        return this.value;
    }

    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof JobDestination && this.value.equals(((JobDestination) other).value));
    }

    @Override
    public int hashCode() {
        return value.hashCode();
    }

    @Override
    public String toString() {
        return value.toString();
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static JobDestination of(WorkbookId value) {
        return new JobDestination(value);
    }
}
