/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flatfile.api.resources.jobs.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.flatfile.api.core.ObjectMappers;
import com.flatfile.api.resources.commons.types.FileId;
import com.flatfile.api.resources.commons.types.JobId;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = JobExecutionPlanConfigRequest.Builder.class)
public final class JobExecutionPlanConfigRequest implements IJobExecutionPlanConfig {
    private final Optional<List<Edge>> fieldMapping;

    private final Optional<List<SourceField>> unmappedSourceFields;

    private final Optional<List<DestinationField>> unmappedDestinationFields;

    private final FileId fileId;

    private final JobId jobId;

    private final Map<String, Object> additionalProperties;

    private JobExecutionPlanConfigRequest(
            Optional<List<Edge>> fieldMapping,
            Optional<List<SourceField>> unmappedSourceFields,
            Optional<List<DestinationField>> unmappedDestinationFields,
            FileId fileId,
            JobId jobId,
            Map<String, Object> additionalProperties) {
        this.fieldMapping = fieldMapping;
        this.unmappedSourceFields = unmappedSourceFields;
        this.unmappedDestinationFields = unmappedDestinationFields;
        this.fileId = fileId;
        this.jobId = jobId;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("fieldMapping")
    @Override
    public Optional<List<Edge>> getFieldMapping() {
        return fieldMapping;
    }

    @JsonProperty("unmappedSourceFields")
    @Override
    public Optional<List<SourceField>> getUnmappedSourceFields() {
        return unmappedSourceFields;
    }

    @JsonProperty("unmappedDestinationFields")
    @Override
    public Optional<List<DestinationField>> getUnmappedDestinationFields() {
        return unmappedDestinationFields;
    }

    @JsonProperty("fileId")
    public FileId getFileId() {
        return fileId;
    }

    @JsonProperty("jobId")
    public JobId getJobId() {
        return jobId;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof JobExecutionPlanConfigRequest && equalTo((JobExecutionPlanConfigRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(JobExecutionPlanConfigRequest other) {
        return fieldMapping.equals(other.fieldMapping)
                && unmappedSourceFields.equals(other.unmappedSourceFields)
                && unmappedDestinationFields.equals(other.unmappedDestinationFields)
                && fileId.equals(other.fileId)
                && jobId.equals(other.jobId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                this.fieldMapping, this.unmappedSourceFields, this.unmappedDestinationFields, this.fileId, this.jobId);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static FileIdStage builder() {
        return new Builder();
    }

    public interface FileIdStage {
        JobIdStage fileId(FileId fileId);

        Builder from(JobExecutionPlanConfigRequest other);
    }

    public interface JobIdStage {
        _FinalStage jobId(JobId jobId);
    }

    public interface _FinalStage {
        JobExecutionPlanConfigRequest build();

        _FinalStage fieldMapping(Optional<List<Edge>> fieldMapping);

        _FinalStage fieldMapping(List<Edge> fieldMapping);

        _FinalStage unmappedSourceFields(Optional<List<SourceField>> unmappedSourceFields);

        _FinalStage unmappedSourceFields(List<SourceField> unmappedSourceFields);

        _FinalStage unmappedDestinationFields(Optional<List<DestinationField>> unmappedDestinationFields);

        _FinalStage unmappedDestinationFields(List<DestinationField> unmappedDestinationFields);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements FileIdStage, JobIdStage, _FinalStage {
        private FileId fileId;

        private JobId jobId;

        private Optional<List<DestinationField>> unmappedDestinationFields = Optional.empty();

        private Optional<List<SourceField>> unmappedSourceFields = Optional.empty();

        private Optional<List<Edge>> fieldMapping = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @Override
        public Builder from(JobExecutionPlanConfigRequest other) {
            fieldMapping(other.getFieldMapping());
            unmappedSourceFields(other.getUnmappedSourceFields());
            unmappedDestinationFields(other.getUnmappedDestinationFields());
            fileId(other.getFileId());
            jobId(other.getJobId());
            return this;
        }

        @Override
        @JsonSetter("fileId")
        public JobIdStage fileId(FileId fileId) {
            this.fileId = fileId;
            return this;
        }

        @Override
        @JsonSetter("jobId")
        public _FinalStage jobId(JobId jobId) {
            this.jobId = jobId;
            return this;
        }

        @Override
        public _FinalStage unmappedDestinationFields(List<DestinationField> unmappedDestinationFields) {
            this.unmappedDestinationFields = Optional.of(unmappedDestinationFields);
            return this;
        }

        @Override
        @JsonSetter(value = "unmappedDestinationFields", nulls = Nulls.SKIP)
        public _FinalStage unmappedDestinationFields(Optional<List<DestinationField>> unmappedDestinationFields) {
            this.unmappedDestinationFields = unmappedDestinationFields;
            return this;
        }

        @Override
        public _FinalStage unmappedSourceFields(List<SourceField> unmappedSourceFields) {
            this.unmappedSourceFields = Optional.of(unmappedSourceFields);
            return this;
        }

        @Override
        @JsonSetter(value = "unmappedSourceFields", nulls = Nulls.SKIP)
        public _FinalStage unmappedSourceFields(Optional<List<SourceField>> unmappedSourceFields) {
            this.unmappedSourceFields = unmappedSourceFields;
            return this;
        }

        @Override
        public _FinalStage fieldMapping(List<Edge> fieldMapping) {
            this.fieldMapping = Optional.of(fieldMapping);
            return this;
        }

        @Override
        @JsonSetter(value = "fieldMapping", nulls = Nulls.SKIP)
        public _FinalStage fieldMapping(Optional<List<Edge>> fieldMapping) {
            this.fieldMapping = fieldMapping;
            return this;
        }

        @Override
        public JobExecutionPlanConfigRequest build() {
            return new JobExecutionPlanConfigRequest(
                    fieldMapping, unmappedSourceFields, unmappedDestinationFields, fileId, jobId, additionalProperties);
        }
    }
}
