/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flatfile.api.resources.jobs.types;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.flatfile.api.core.ObjectMappers;
import java.io.IOException;
import java.util.Objects;

@JsonDeserialize(using = JobParts.Deserializer.class)
public final class JobParts {
    private final Object value;

    private final int type;

    private JobParts(Object value, int type) {
        this.value = value;
        this.type = type;
    }

    @JsonValue
    public Object get() {
        return this.value;
    }

    public <T> T visit(Visitor<T> visitor) {
        if (this.type == 0) {
            return visitor.visit((int) this.value);
        } else if (this.type == 1) {
            return visitor.visit((JobPartsArray) this.value);
        }
        throw new IllegalStateException("Failed to visit value. This should never happen.");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof JobParts && equalTo((JobParts) other);
    }

    private boolean equalTo(JobParts other) {
        return value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.value);
    }

    @java.lang.Override
    public String toString() {
        return this.value.toString();
    }

    public static JobParts of(int value) {
        return new JobParts(value, 0);
    }

    public static JobParts of(JobPartsArray value) {
        return new JobParts(value, 1);
    }

    public interface Visitor<T> {
        T visit(int value);

        T visit(JobPartsArray value);
    }

    static final class Deserializer extends StdDeserializer<JobParts> {
        Deserializer() {
            super(JobParts.class);
        }

        @java.lang.Override
        public JobParts deserialize(JsonParser p, DeserializationContext ctxt) throws IOException {
            Object value = p.readValueAs(Object.class);
            if (value instanceof Integer) {
                return of((Integer) value);
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, JobPartsArray.class));
            } catch (IllegalArgumentException e) {
            }
            throw new JsonParseException(p, "Failed to deserialize");
        }
    }
}
