/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flatfile.api.resources.jobs.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;
import java.util.Optional;

public final class JobSubject {
    private final Value value;

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    private JobSubject(Value value) {
        this.value = value;
    }

    public <T> T visit(Visitor<T> visitor) {
        return value.visit(visitor);
    }

    public static JobSubject resource(ResourceJobSubject value) {
        return new JobSubject(new ResourceValue(value));
    }

    public static JobSubject collection(CollectionJobSubject value) {
        return new JobSubject(new CollectionValue(value));
    }

    public boolean isResource() {
        return value instanceof ResourceValue;
    }

    public boolean isCollection() {
        return value instanceof CollectionValue;
    }

    public boolean _isUnknown() {
        return value instanceof _UnknownValue;
    }

    public Optional<ResourceJobSubject> getResource() {
        if (isResource()) {
            return Optional.of(((ResourceValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CollectionJobSubject> getCollection() {
        if (isCollection()) {
            return Optional.of(((CollectionValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<Object> _getUnknown() {
        if (_isUnknown()) {
            return Optional.of(((_UnknownValue) value).value);
        }
        return Optional.empty();
    }

    @JsonValue
    private Value getValue() {
        return this.value;
    }

    public interface Visitor<T> {
        T visitResource(ResourceJobSubject resource);

        T visitCollection(CollectionJobSubject collection);

        T _visitUnknown(Object unknownType);
    }

    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type", visible = true, defaultImpl = _UnknownValue.class)
    @JsonSubTypes({@JsonSubTypes.Type(ResourceValue.class), @JsonSubTypes.Type(CollectionValue.class)})
    @JsonIgnoreProperties(ignoreUnknown = true)
    private interface Value {
        <T> T visit(Visitor<T> visitor);
    }

    @JsonTypeName("resource")
    private static final class ResourceValue implements Value {
        @JsonUnwrapped
        private ResourceJobSubject value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private ResourceValue() {}

        private ResourceValue(ResourceJobSubject value) {
            this.value = value;
        }

        @Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitResource(value);
        }

        @Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof ResourceValue && equalTo((ResourceValue) other);
        }

        private boolean equalTo(ResourceValue other) {
            return value.equals(other.value);
        }

        @Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @Override
        public String toString() {
            return "JobSubject{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("collection")
    private static final class CollectionValue implements Value {
        @JsonUnwrapped
        private CollectionJobSubject value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private CollectionValue() {}

        private CollectionValue(CollectionJobSubject value) {
            this.value = value;
        }

        @Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitCollection(value);
        }

        @Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof CollectionValue && equalTo((CollectionValue) other);
        }

        private boolean equalTo(CollectionValue other) {
            return value.equals(other.value);
        }

        @Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @Override
        public String toString() {
            return "JobSubject{" + "value: " + value + "}";
        }
    }

    private static final class _UnknownValue implements Value {
        private String type;

        @JsonValue
        private Object value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private _UnknownValue(@JsonProperty("value") Object value) {}

        @Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor._visitUnknown(value);
        }

        @Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof _UnknownValue && equalTo((_UnknownValue) other);
        }

        private boolean equalTo(_UnknownValue other) {
            return type.equals(other.type) && value.equals(other.value);
        }

        @Override
        public int hashCode() {
            return Objects.hash(this.type, this.value);
        }

        @Override
        public String toString() {
            return "JobSubject{" + "type: " + type + ", value: " + value + "}";
        }
    }
}
