/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flatfile.api.resources.auth.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.flatfile.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = DeleteApiKeyRequest.Builder.class)
public final class DeleteApiKeyRequest {
    private final String environmentId;

    private final String key;

    private final Map<String, Object> additionalProperties;

    private DeleteApiKeyRequest(String environmentId, String key, Map<String, Object> additionalProperties) {
        this.environmentId = environmentId;
        this.key = key;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("environmentId")
    public String getEnvironmentId() {
        return environmentId;
    }

    @JsonProperty("key")
    public String getKey() {
        return key;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DeleteApiKeyRequest && equalTo((DeleteApiKeyRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DeleteApiKeyRequest other) {
        return environmentId.equals(other.environmentId) && key.equals(other.key);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.environmentId, this.key);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static EnvironmentIdStage builder() {
        return new Builder();
    }

    public interface EnvironmentIdStage {
        KeyStage environmentId(String environmentId);

        Builder from(DeleteApiKeyRequest other);
    }

    public interface KeyStage {
        _FinalStage key(String key);
    }

    public interface _FinalStage {
        DeleteApiKeyRequest build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements EnvironmentIdStage, KeyStage, _FinalStage {
        private String environmentId;

        private String key;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @Override
        public Builder from(DeleteApiKeyRequest other) {
            environmentId(other.getEnvironmentId());
            key(other.getKey());
            return this;
        }

        @Override
        @JsonSetter("environmentId")
        public KeyStage environmentId(String environmentId) {
            this.environmentId = environmentId;
            return this;
        }

        @Override
        @JsonSetter("key")
        public _FinalStage key(String key) {
            this.key = key;
            return this;
        }

        @Override
        public DeleteApiKeyRequest build() {
            return new DeleteApiKeyRequest(environmentId, key, additionalProperties);
        }
    }
}
