/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flatfile.api.resources.files.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum Mode {
    IMPORT("import"),

    EXPORT("export");

    private final String value;

    Mode(String value) {
        this.value = value;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
