/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.flatfile.api.resources.dataretentionpolicies.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.flatfile.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = DataRetentionPolicyConfig.Builder.class)
public final class DataRetentionPolicyConfig implements IDataRetentionPolicyConfig {
    private final DataRetentionPolicyEnum type;

    private final int period;

    private final Map<String, Object> additionalProperties;

    private DataRetentionPolicyConfig(
            DataRetentionPolicyEnum type, int period, Map<String, Object> additionalProperties) {
        this.type = type;
        this.period = period;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("type")
    @Override
    public DataRetentionPolicyEnum getType() {
        return type;
    }

    @JsonProperty("period")
    @Override
    public int getPeriod() {
        return period;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DataRetentionPolicyConfig && equalTo((DataRetentionPolicyConfig) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DataRetentionPolicyConfig other) {
        return type.equals(other.type) && period == other.period;
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.type, this.period);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TypeStage builder() {
        return new Builder();
    }

    public interface TypeStage {
        PeriodStage type(DataRetentionPolicyEnum type);

        Builder from(DataRetentionPolicyConfig other);
    }

    public interface PeriodStage {
        _FinalStage period(int period);
    }

    public interface _FinalStage {
        DataRetentionPolicyConfig build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TypeStage, PeriodStage, _FinalStage {
        private DataRetentionPolicyEnum type;

        private int period;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @Override
        public Builder from(DataRetentionPolicyConfig other) {
            type(other.getType());
            period(other.getPeriod());
            return this;
        }

        @Override
        @JsonSetter("type")
        public PeriodStage type(DataRetentionPolicyEnum type) {
            this.type = type;
            return this;
        }

        @Override
        @JsonSetter("period")
        public _FinalStage period(int period) {
            this.period = period;
            return this;
        }

        @Override
        public DataRetentionPolicyConfig build() {
            return new DataRetentionPolicyConfig(type, period, additionalProperties);
        }
    }
}
